FORMAT: 1A
HOST: https://omniapi.varner.com/

# Varner Omni API reference

Varner Omni API is a service for placing orders in the webshop. The API is based on REST.
<br/>
<br/>
<b>Allowed HTTPs requests</b><br/>
POST    : Create resource <br>
PUT     : Update resource<br>
GET     : Get a resource or list of resources<br>
DELETE  : Delete resource<br>
<br/>
<br/>
<b>Description Of Usual Server Responses</b>
<ul>
<li>
<p>200 <code>OK</code> - the request was successful (some API calls may return 201 instead).</p>
</li>
<li>
<p>201 <code>Created</code> - the request was successful and a resource was created.</p>
</li>
<li>
<p>204 <code>No Content</code> - the request was successful but there is no representation to return (i.e. the response is empty).</p>
</li>
<li>
<p>400 <code>Bad Request</code> - the request could not be understood or was missing required parameters.</p>
</li>
<li>
<p>401 <code>Unauthorized</code> - authentication failed or user doesn't have permissions for requested operation.</p>
</li>
<li>
<p>403 <code>Forbidden</code> - access denied.</p>
</li>
<li>
<p>404 <code>Not Found</code> - resource was not found.</p>
</li>
<li>
<p>405 <code>Method Not Allowed</code> - requested method is not supported for resource.</p>
</li>
</ul>

# Varner Omni API Root [/]

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "skusUrl": "/omni/products/skus/",
            "deliveryUrl": "/omni/delivery/",
            "orderUrl": "/omni/order/",
            "prelorderUrl": "/omni/order/prelorder"
        }

## Article  [/omni/products/skus/{skuid}]

### Get Product Information [GET]

Get price and stock information by sku id.

<b>Response</b>

+ `skuId` (string) : Id of sku.
+ `price` (number) : Sku price.
+ `stock` (number) : Current available stock for sku.

+ Parameters
    + skuid: 7050222348681 (string, required) - Id of the sku
    
+ Response 200 (application/json)

        {
            "skuId": "7050222348681",
            "price": 79,
            "stock": 50
        }


## Article collection  [/omni/products/skus]

### Get Product Information for multiple skus [POST]

Get price and stock information for multiple skus.

+ `skus` (string) : Comma separated list of skus, ex: 7050222348681,7050225553241

<b>Response</b><br>
Array of skus

+ Request (application/json)
    + Attributes (object)
        + skus: 7050222348681,7050225553241 (string, required) - Comma separated list of sku id's.
     
+ Response 200 (application/json)

        [
            {
                "skuId": "7050222348681",
                "price": 79,
                "stock": 50
            },
            {
                "skuId": "7050225553241",
                "price": 149,
                "stock": 10
            }
        ]


## Shipping  [/omni/delivery/{zip}{?provider}{?take}]

+ Parameters
    + zip: 21500  (required, string) - Customer zipcode.
    + provider: pickupinstore  (optional, string) - Filter on delivery provider.
    + take: 3 (optional, number) - The number of delivery options to return.


### Get Delivery Methods [GET]

Get delivery methods available for a given zipcode.

<b>Response</b>

+ <code>type</code> (string) : Type of delivery method, currently three options: <code>Standard</code> <code>Express</code> <code>PickupInStore</code>.
+ <code>name</code> (string) : Name of delivery method as displayed in webshop. 
+ <code>placeOfDeliveries</code> (array) : List of delivery places.
+ <code>name</code> (string) : Name of delivery place.
+ <code>address</code> (string) : Address of delivery place.
+ <code>code</code> (string) : Code of delivery place.

+ Response 200 (application/json)

    + Body

            [
                {   
                    "type": "Standard",
                    "name": "Standardleverans / PostNord (1-3 arbetsdagar)",
                    "placeOfDeliveries": [
                        {
                            "name": "Nallens Livs",
                            "address": "Sevedsgatan 10, 21445, Malmö",
                            "code": "170573"
                        }, {
                            "name": "Ica Malmborgs Mobilia",
                            "address": " Per Albin Hanssons Väg 40, 21432, Malmö",
                            "code": "170575"
                        }
                    ]
                },
                {   
                    "type": "Express",
                    "name": "Dörr till Dörr / DHL"
                },   
                {   
                    "type": "PickupInStore",
                    "name": "Hämta i Cubus-butik (Gratis)",
                    "placeOfDeliveries": [
                        {
                            "name": "Cubus Malmö centrum",
                            "address": "Södra Förstadsgatan 32, 211 43, Malmö",
                            "code": "R04"
                        }, {
                            "name": "Cubus Nordstan",
                            "address": "Götgatan 13, 411 05, Göteborg",
                            "code": "C76"
                        }
                    ]
                }  
            ]

## Preleminary Order [/omni/order/prelorder]

+ Attributes (Preleminary Order Base )
  

### Create a New Preleminary Order [POST]

Creates the preleminary order and calculates the shipping fee.
The order id that is returned should be used when the preleminary order needs to be updated.
 
 <b>Response</b>
 
 + <code>orderId</code> (string) : Preleminary order id. This is used when updating the preleminary order.
 + <code>shippingFee</code> (number) : Total shipping fee for order.
 + <code>items</code> (array) : Items in order. Quantity might change if item runs of out stock.

+ Attributes (Preleminary Order Base )

+ Request (application/json)

        + Attributes (Preleminary Order Base )

+ Response 201 (application/json)

    + Attributes (object)
         + orderId: 334564654 (string) - The preleminary order id
         + shippingFee: 90 (number) - The shipping fee 
         + `items` (array) - Items in order
             + (Lineitem)
             + (Lineitem2)

## Existing Preleminary Order [/omni/order/prelorder/{orderid}]

+ Parameters 
   + orderid: 353453453 (string, required) - Preleminary order id.


### Update a Preleminary Order [PUT]

Updates the preliminary order.

+ Attributes (Preleminary Order Base )

+ Request (application/json)

        + Attributes (Preleminary Order Base )
        
+ Response 200 (application/json)

    + Attributes (object)
         + orderId: 334564654 (string) - The preleminary order id
         + shippingFee: 90 (number) - The shipping fee 
         + `items` (array) - Items in order
             + (Lineitem)
             + (Lineitem2)

            
            
### Delete a Preleminary Order [DELETE]
+ Response 200

        { 
            "result": True
        }
        

## Order [/omni/order/{orderid}]

+ Parameters
    + orderid: 334564654 (string, required) - The preleminary order id.
    
### Create Order [POST]

Turns a preleminary order into an actual order. 
Must include the transaction reference from NETS in the request.


<b>Response</b>

+ `orderNumber` (string) : Ordernumber in webshop.

+ Request (application/json)

    + Attributes (object)
         + transactionId : 5766573453487686 (string, required) - Transaction reference from NETS.

+ Response 201

        { 
            "orderNumber": "334564654"
        }
        
        
# Data Structures

## Preleminary Order Base (object)

+ referenceReceiptNo: 82789274823 (string, required) - Facta Pos receipt reference.
+ shippingMethod : PickupInStore (string, required) - Type returned from GetDeliveryMethods.
+ placeOfDeliveryCode : C76 (string) - The location id for where the order should be delivered.
 Required if ShippingMethod is `Standard` or `PickupInStore`.
+ address (Address) - Customer information
+ `items` (array, required) - Items in order
    + (Lineitem)
    + (Lineitem2)
+ shippingFee (number) - Should be used if shipping fee is decided by salesperson.
+ totalSum : 599.00 (number, required) - Total sum of all items in order. This will be used for calculating shipment cost.

       

## Address (object)
+ firstName : Fredrik (string, required) - Customer's first name.
+ lastName : Lastnamesson (string, required) - Customer's last name.
+ crmId : 23243324 (string) - Customer's id in CRM system.
+ email : customer@ateles.se (string, required) - Customer's email.
+ mobilePhone : 0701234567 (string, required) - Customer's phone number. Prefix can be provided (with +) or else it will be added based on customer's country.
+ street : Road 6 (string, required) - Customer's street address.
+ street2 : substreet (string) - Can be provided if multiple address lines.
+ zip : 58330 (string, required) - Customer's zip code.
+ city : Gotham City (string, required) - Customer's city.
+ countryCode : NO (string, required) - Customer's country code (two letter ISO 3166-2).

## Lineitem (object)
+ skuId : 734234234 (string, required) - Sku id of ordered item. 
+ quantity : 1 (number, required) - Quantity ordered of sku. 
+ price : 129.00 (number, required) - Sku price (included discount). 

## Lineitem2 (object)
+ skuId : 776554546 (string, required) - Sku id of ordered item. 
+ quantity : 2 (number, required) - Quantity ordered of sku. 
+ price : 340.00 (number, required) - Sku price (included discount).