FORMAT: 1A
HOST: https://omniapi.varner.com/

# Varner Omni API reference

Varner Omni API is a service for placing orders in the webshop. The API is based on REST.
<br/>
<br/>
<b>Allowed HTTPs requests</b><br/>
POST    : Create resource <br>
PUT     : Update resource<br>
GET     : Get a resource or list of resources<br>
DELETE  : Delete resource<br>
<br/>
<br/>
<b>Description Of Usual Server Responses</b>
<ul>
<li>
<p>200 <code>OK</code> - the request was successful (some API calls may return 201 instead).</p>
</li>
<li>
<p>201 <code>Created</code> - the request was successful and a resource was created.</p>
</li>
<li>
<p>204 <code>No Content</code> - the request was successful but there is no representation to return (i.e. the response is empty).</p>
</li>
<li>
<p>400 <code>Bad Request</code> - the request could not be understood or was missing required parameters.</p>
</li>
<li>
<p>401 <code>Unauthorized</code> - authentication failed or user doesn't have permissions for requested operation.</p>
</li>
<li>
<p>403 <code>Forbidden</code> - access denied.</p>
</li>
<li>
<p>404 <code>Not Found</code> - resource was not found.</p>
</li>
<li>
<p>405 <code>Method Not Allowed</code> - requested method is not supported for resource.</p>
</li>
</ul>

# Varner Omni API Root [/]

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "skusUrl": "/{language}/{chain}/{storeId}/products/skus/",
            "deliveryUrl": "/{language}/{chain}/{storeId}/delivery/",
            "orderUrl": "/{language}/{chain}/{storeId}/order/",
            "prelorderUrl": "/{language}/{chain}/{storeId}/order/prelorder"
        }

## Article  [/{language}/{chain}/{storeId}/products/skus/{skuid}]

### Get Product Information [GET]

Get price and stock information by sku id.

<b>Response</b>

+ `skuId` (string) : Id of sku.
+ `price` (number) : Sku price.
+ `stock` (number) : Current available stock for sku.

+ Parameters
    + language : se (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store.
    + skuid: 7050222348681 (string, required) - Id of the sku
    
+ Response 200 (application/json)

        {
            "skuId": "7050222348681",
            "listPrice": 79,
            "salesPrice": 79,
            "stock": 50
        }


## Article collection  [/{language}/{chain}/{storeId}/products/skus]

### Get Product Information for multiple skus [POST]

Get price and stock information for multiple skus.

<b>Response</b><br>
Array of sku id's

+ Parameters
    + language : se (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store.

+ Request (application/json)
        
        ["71862860006", "71862860002"]
     
+ Response 200 (application/json)

        [
            {
                "skuId": "7050222348681",
                "listPrice": 79,
                "salesPrice": 79,
                "stock": 50
            },
            {
                "skuId": "7050225553241",
                "listPrice": 149,
                "salesPrice": 149,
                "stock": 10
            }
        ]


## Shipping  [/{language}/{chain}/{storeId}/delivery/{zip}{?take}]

+ Parameters
    + language : no (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store.
    + zip: 1353  (required, string) - Customer zipcode.
    + take: 3 (optional, number) - The number of delivery options to return.


### Get Delivery Methods [GET]

Get delivery methods available for a given zipcode.

<b>Response</b>

+ `type` (string) : Type of delivery method, currently three options: <code>Standard</code> <code>Express</code> <code>PickupInStore</code>.
+ `name` (string) : Name of delivery method as displayed in webshop. 
+ `deliveryId` (string) : System id for delivery method.
+ `shippingFee` (string) : Price of delivery method.
+ `placeOfDeliveries` (array) : List of delivery places.
+ `name` (string) : Name of delivery place.
+ `address` (string) : Address of delivery place.
+ `placeOfDeliveryCode` (string) : Code of delivery place.

+ Response 200 (application/json)

    + Body

            [
                {   
                    "type": "Standard",
                    "name": "Standardleverans / PostNord (1-3 arbetsdagar)",
                    "deliveryId": "r723fb46e-e34e-4c2b-9333-267cabcaf433",
                    "shippingFee": 49,
                    "placeOfDeliveries": [
                        {
                            "name": "Nallens Livs",
                            "address": "Sevedsgatan 10, 21445, Malmö",
                            "placeOfDeliveryCode": "170573"
                        }, {
                            "name": "Ica Malmborgs Mobilia",
                            "address": " Per Albin Hanssons Väg 40, 21432, Malmö",
                            "placeOfDeliveryCode": "170575"
                        }
                    ]
                },
                {   
                    "type": "Express",
                    "name": "Dörr till Dörr / DHL",
                    "deliveryId": "c3866549-17e8-4784-b5ea-1cf78c5dd4d5",
                    "shippingFee": 149
                },   
                {   
                    "type": "PickupInStore",
                    "name": "Hämta i Cubus-butik (Gratis)",
                    "deliveryId": "4624010c-3fb0-4d3e-af98-3bf43c7bba3b",
                    "shippingFee": 0,
                    "placeOfDeliveries": [
                        {
                            "name": "Cubus Malmö centrum",
                            "address": "Södra Förstadsgatan 32, 211 43, Malmö",
                            "placeOfDeliveryCode": "R04"
                        }, {
                            "name": "Cubus Nordstan",
                            "address": "Götgatan 13, 411 05, Göteborg",
                            "placeOfDeliveryCode": "C76"
                        }
                    ]
                }  
            ]

## Preleminary Order [/{language}/{chain}/{storeId}/order/prelorder]

+ Parameters
    + language : se (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store.
    
+ Attributes (Preleminary Order Base )



### Create a New Preleminary Order [POST]

Creates the preleminary order and calculates the shipping fee.
The order id that is returned should be used when the preleminary order needs to be updated.
 
 <b>Response</b>
 
 + `valid` (string) : Status of creating the preleminary order.
 + `validationMessage` (string) : If not `valid` a validationMessage will be included.
 + `orderId` (string) : Preleminary order id. This is used when updating the preleminary order.
 + `shippingFee` (number) : Total shipping fee for order.
 + `items` (array) : Items in order. Quantity might change if item runs of out stock.

+ Request (application/json)

    + Attributes (Preleminary Order Base )

+ Response 201 (application/json)

    + Attributes (Preleminary Order Result)
 

## Existing Preleminary Order [/{language}/{chain}/{storeId}/order/prelorder/{orderid}]

+ Parameters
    + language : se (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store. 
    + orderid: 353453453 (string, required) - Preleminary order id.


### Update a Preleminary Order [PUT]

Updates the preliminary order.


+ Request (application/json)

        + Attributes (Preleminary Order Base )
        
+ Response 200 (application/json)

    + Attributes (Preleminary Order Result )
         
            
            
### Delete a Preleminary Order [DELETE]
+ Response 200

        { 
            "result": True
        }
        

## Order [/{language}/{chain}/{storeId}/order/{orderid}]

+ Parameters
    + language : se (string, required) - Two letter country code.
    + chain : cubus (string, required) - Name of chain.
    + storeId : 514 (string, required) - Id of store. 
    + orderid: 334564654 (string, required) - The preleminary order id.
    
### Create Order [POST]

Turns a preleminary order into an actual order. 
Requires a `valid` status response from Create/Update Preleminary Order.
Must include the transaction reference from NETS in the request.


<b>Response</b>

+ `orderNumber` (string) : Ordernumber in webshop.
+ `receiptId` (string) : Receipt id in webshop.

+ Request (application/json)

    + Attributes (object)
         + capturePaymentToken : 5766573453487686 (string, required) - Transaction token from NETS.

+ Response 201

        { 
            "orderNumber": "CU-8WS-1709596",
            "receiptId": "3011709636"
        }
        
        
# Data Structures

## Preleminary Order Base (object)

+ referenceReceiptNo: 82789274823 (string, required) - Facta Pos receipt reference.
+ sellerId: 112 (string, required) - Id of seller.
+ deliveryId : 4624010c-3fb0-4d3e-af98-3bf43c7bba3b (string, required) - DeliveryId returned from GetDeliveryMethods.
+ placeOfDeliveryCode : C76 (string) - The location id for where the order should be delivered.
 Required if ShippingMethod is `Standard` or `PickupInStore`.
+ address (Address) - Customer information
+ `items` (array, required) - Items in order
    + (Lineitem)
    + (Lineitem2)
+ shippingFee (number) - Should be used if shipping fee is decided by salesperson.
+ totalSum : 599.00 (number, required) - Total sum of all items in order. This will be used for calculating shipment cost.

       
## Preleminary Order Result (object)
+ valid: true (string) - Status of creating the preleminary order.
+ validationMessage (string) - If not valid a validationMessage will be included.
+ orderId: 334564654 (string) - The preleminary order id
+ shippingFee: 90 (number) - Total shipping fee for order.
+ `items` (array) - Items in order. Quantity might change if item runs of out stock.
     + (Lineitem)
     + (Lineitem2)
             
## Address (object)
+ firstName : Fredrik (string, required) - Customer's first name.
+ lastName : Lastnamesson (string, required) - Customer's last name.
+ crmId : 23243324 (string) - Customer's id in CRM system.
+ email : customer@ateles.se (string, required) - Customer's email. Email should be validated to have a valid format.
+ mobilePhone : 0701234567 (string, required) - Customer's phone number.
+ street : Road 6 (string, required) - Customer's street address.
+ street2 : C/O adress (string) - Can be provided if C/O adress or multiple address lines.
+ zip : 58330 (string, required) - Customer's zip code.
+ city : Gotham City (string, required) - Customer's city.

## Lineitem (object)
+ skuId : 734234234 (string, required) - Sku id of ordered item. 
+ quantity : 1 (number, required) - Quantity ordered of sku. 
+ price : 129.00 (number, required) - Sales price. 

## Lineitem2 (object)
+ skuId : 776554546 (string, required) - Sku id of ordered item. 
+ quantity : 2 (number, required) - Quantity ordered of sku. 
+ price : 340.00 (number, required) - Sales price.